---
global:
  postgresqlSecretName: "dagster-postgresql-secret"
  postgresqlAuthWifEnabled: false
  dagsterHome: "/opt/dagster/dagster_home"
  serviceAccountName: ""
  celeryConfigSecretName: "dagster-celery-config-secret"
  dagsterInstanceConfigMap: ""

dagsterHome: "/opt/dagster/dagster_home"
postgresqlSecretName: "dagster-postgresql-secret"
celeryConfigSecretName: "dagster-celery-config-secret"

deployments:
- name: "gadgetbridge"
  image:
    repository: "ghcr.io/leprechaun/dagster-gadgetbridge"
    tag: "VERSION"
    pullPolicy: Always

  dagsterApiGrpcArgs:
    - "--python-file"
    - "/deploy_k8s/src/gadgetbridge_pipeline/definitions.py"
  port: 3030
  envSecrets:
    - name: gadgetbridge
